language: python
python:
  # - "2.7"
  - "3.5"
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -q -n test-environment python=$TRAVIS_PYTHON_VERSION -f env.yml
  - source activate test-environment

script:
  - python helmsman.py --mode vcf --input data/chr22.16050075-16992642.1kg.phase3.vcf.gz --fastafile data/chr22.fasta.gz --decomp nmf --rank 4 --package deconstructSigs --verbose
  - python helmsman.py --mode agg --input data/gsc_LIHC.subtype_count_matrix.txt --decomp pca --rank 4 --package SomaticSignatures --verbose
