site_name: helmsman
site_url: https://github.com/carjed/helmsman
repo_url: https://github.com/carjed/helmsman
nav:
  - Home: index.md
  - Usage: usage.md
  - FAQ: faq.md
  - Support: support.md
theme: cinder
